name: agentic-ux
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - uvicorn
  - fastapi
  - pydantic
  - httpx
  - python-dotenv
  - aiofiles
  - python-multipart
  - pip:
      - langchain
      - openai
      - supabase
      - whisper
      - python-docx
      - jinja2
      - pdfkit
      - PyMuPDF
      - psycopg[binary]
      - firebase-admin
      - python-jose
      - python-magic
